import Head from "next/head";
import Image from "next/image";
// import Sidebar from "@/components/Sidebar";
import TopCards from "@/components/TopCards";
import BarChart from "@/components/BarChart";
import RecentStocks from "@/components/RecentStocks";
import Header from "@/components/Header";
import Custom from "./custom";
// import Sidebar from "@/components/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Truffles - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 min-h-screen">
        <Custom />
        {/* <Header /> */}
        {/* <Sidebar /> */}
        {/* <TopCards /> */}
        {/* <Sidebar /> */}
        <div className="p-4 grid md:grid-cols-3 grid-cols-1 gap-4">
          {/* <BarChart /> */}
          {/* <RecentOrders /> */}
        </div>
      </main>
    </>
  );
}
